# C locale
export LANG=C

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Theme
source "$HOME/.nix-profile/share/zsh-powerlevel10k/powerlevel10k.zsh-theme"
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source "$HOME/.p10k.zsh"

# ZSH options
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt HIST_IGNORE_ALL_DUPS
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.

# Autocompletion
autoload -U compinit && compinit
zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'r:|?=** m:{a-z\-}={A-Z\_}'  # fuzzy autocomplete
setopt auto_menu
   
# Command editing
autoload -U edit-command-line
zle -N edit-command-line
bindkey -e
bindkey '\C-x\C-e' edit-command-line

# gpg
export GPG_TTY=$TTY

# aliases
alias l="ls -lah --color=auto"
alias vim="nvim"
alias v="nvim"
alias vimdiff="nvim -d"
alias vimr="vimr --cur-env"
alias c="clear"
alias ykswap="gpg-connect-agent 'scd serialno' 'learn --force' /bye"
alias yk="ykman"
alias d="docker"
alias t="terraform"
alias p="popd"
alias pll="parallel"
alias j="jira"

# Changing/making/removing directory
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus

alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'
alias -g ......='../../../../..'

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# FZF
# ---
export FZF_DEFAULT_COMMAND='fd --hidden --follow --type f --exclude ".git" --exclude ".tags"'

if [ -n "${commands[fzf-share]}" ]; then
  source "$(fzf-share)/key-bindings.zsh"
  source "$(fzf-share)/completion.zsh"
  export FZF_DEFAULT_OPTS='--color=fg+:21,bg+:-1,pointer:21,hl:2,hl+:2'
  export FZF_COMPLETION_TRIGGER=''
  bindkey '^T' fzf-completion
  bindkey '^I' "$fzf_default_completion"

  # Path and directory completion
  # - The first argument to the function ($1) is the base path to start traversal
  _fzf_compgen_path() {
    fd --hidden --follow --type f --exclude ".git" --exclude ".tags" . "$1"
  }

  # Use fd to generate the list for directory completion
  _fzf_compgen_dir() {
    fd --maxdepth 3 --type d --hidden --follow --exclude ".git" --exclude ".tags" . "$1"
  }

  _fzf_complete_fg() {
    _fzf_complete \
      --reverse \
      --height=40% -- "$@" < <(jobs -l)
  }

  _fzf_complete_fg_post() {
    sed -E 's/^\[([0-9]+)\].*$/%\1/'
  }
fi

# extra ergonomics things
source "$HOME/.k8s.zsh"
source "$HOME/.git.zsh"

# custom executable scripts
export PATH=$PATH:$HOME/bin

# go bin path
export PATH=$PATH:$HOME/go/bin
