[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.normal]
family = "Fira Code"
style = "Regular"

# \u0013 is the hex code for Ctrl-S, my tmux prefix.
[[keyboard.bindings]]
chars = "\u0013n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0013p"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0013c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013[?"
key = "F"
mods = "Command"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1

[window.padding]
x = 8
y = 8
