env:
  TERM: alacritty
window:
  padding:
    x: 8
    y: 8
  decorations: buttonless
  opacity: 1
  dynamic_padding: true
font:
  normal:
    family: Fira Code
    style: Regular
  size: 12.0
# \x13 is the escape sequence for control+s (my tmux prefix)
key_bindings:
  - { key: Tab, mods: Control, chars: "\x13n" } # tmux next pane
  - { key: Tab, mods: Control|Shift, chars: "\x13p" } # tmux prev pane
  - { key: T, mods: Command, chars: "\x13c" } # tmux new pane
  - { key: W, mods: Command, chars: "\x13x" } # tmux close pane
  - { key: F, mods: Command, chars: "\x13[?" } # tmux search up
colors:
  cursor:
    text: "CellBackground"
    cursor: "CellForeground"
