env:
  TERM: alacritty
window:
  padding:
    x: 8
    y: 8
  decorations: buttonless
  opacity: 1
  dynamic_padding: true
font:
  normal:
    family: Fira Code
    style: Regular
  size: 14.0
# \x13 is the escape sequence for control+s (my tmux prefix) 
key_bindings:
  - {key: Tab, mods: Control, chars: "\x13n"} # tmux next window
  - {key: Tab, mods: Control|Shift, chars: "\x13p"} # tmux prev window
colors:
  cursor:
    text: "CellBackground"
    cursor: "CellForeground"
